import type { Metadata } from 'next'
import './index.css'
import { FCWithChildren } from '@/shared/@types'
import StoreProvider from './providers/store-provider'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const RootLayout: FCWithChildren = ({ children }) => (
  <html lang='en'>
    <body className={inter.className}>
      <StoreProvider>{children}</StoreProvider>
    </body>
  </html>
)

export default RootLayout
