import type { Metadata } from 'next'
import './index.css'
import { FCWithChildren } from '@/shared/@types'
import StoreProvider from './providers/store-provider'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const RootLayout: FCWithChildren = ({ children }) => (
  <html lang='en'>
    <body>
      <StoreProvider>{children}</StoreProvider>
    </body>
  </html>
)

export default RootLayout
